version: "3"

services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: ".env"
    environment:
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
      - PG_DATA:/var/lib/postgresql/data
    ports:
    - 5432:5432

  web:
    working_dir: /code/apps
    build: .
    volumes:
      - .:/code/
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on: 
      - db
    env_file: .env
  